[default]
description = "Default permissions for the plugin"
permissions = ["allow-ping", "allow-download-private", "allow-download-public", "allow-save-file-private-from-path", "allow-save-file-public-from-path"]
